name: nshop-docker-ci

on:
  push:
    branches:
      - 'cicd'
  pull_request:
    branches:
      - 'main'

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:

      - name: 저장소 Checkout
        uses: actions/checkout@v4

      - name: 자바 17 setup
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '17'

      - name: application.yml 파일 생성
        run: |
          mkdir ./src/main/resources # resources 폴더 생성
          cd ./src/main/resources # resources 폴더로 이동
          touch ./application.yml # application.yml 생성
          echo "${{ secrets.YML }}" > ./application.yml # github actions에서 설정한 값을 application.yml 파일에 쓰기
        shell: bash

      - name: application-prod.yml 파일 생성
        run: |
          cd ./src/main/resources # resources 폴더로 이동
          touch ./application-prod.yml # application-prod.yml 생성
          echo "${{ secrets.YML_prod }}" > ./application-prod.yml # github actions에서 설정한 값을 application.yml 파일에 쓰기
        shell: bash

      - name: application-dev.yml 파일 생성
        run: |
          cd ./src/main/resources # resources 폴더로 이동
          touch ./application-dev.yml # application-dev.yml 생성
          echo "${{ secrets.YML_DEV }}" > ./application-dev.yml # github actions에서 설정한 값을 application.yml 파일에 쓰기
        shell: bash

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: 스프링부트 애플리케이션 빌드
        run: ./gradlew clean build -Pprofile=prod

      - name: 도커 이미지 빌드
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/nshop-repo .
        
      - name: Docker Hub 로그인
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker Hub 퍼블리시
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/nshop-repo
      
      - name: EC2 접속 및 docker-compose.yml 파일 전송 및 실행
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          
          script: |
            cd /home/ubuntu
            echo "${{ secrets.DOCKER_COMPOSE }}" > docker-compose.yml # github secrets에 설정한 DOCKER_COMPOSE 파일을 생성한다.
            docker-compose down
            docker-compose pull
            docker-compose up -d
            # 현재 실행중이 아닌 12시간 이상 컨테이너 이미지 삭제
            docker image prune -f --filter "until=12h"
            
